---
name: Test MLSYNTH
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate_plots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .  # Install the mlsynth module from your local repository

      - name: Run FDID Basque and move plot
        run: |
          set -x
          python examples/fdidbasque.py

      - name: Run GermanyCLUSTERSC and move plot
        run: |
          set -x
          python examples/GermanyCLUSTERSC.py

      - name: Run PanelData
        run: |
          set -x
          python examples/paneldata.py

      - name: Commit plots
        run: |
          git add -A  # Stage all changes
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git diff --exit-code --quiet || git commit -m "Add updated plots"

      - name: Pull changes from the remote repository before pushing
        run: |
          git add . 
          git commit -m "Committing staged changes before pull" || echo "No changes to commit"
          git pull https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git main --rebase

      - name: Push the changes to the repository
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jgreathouse9/mlsynth.git HEAD:main
